#!/usr/bin/env bash

# Shared reward definition for training and common-verifier offline rescoring.
export GOV_MISSING_TOOL_PENALTY="${GOV_MISSING_TOOL_PENALTY:-0.45}"
export GOV_MISSING_TOOL_HARD_GATE="${GOV_MISSING_TOOL_HARD_GATE:-1}"
export GOV_DECISION_GATE_CEILING="${GOV_DECISION_GATE_CEILING:-0.0}"
export GOV_PROCESS_GATE_CEILING="${GOV_PROCESS_GATE_CEILING:-0.10}"
export GOV_INVALID_SLOT_PENALTY="${GOV_INVALID_SLOT_PENALTY:-0.15}"
export GOV_ILLEGAL_ACTION_PENALTY="${GOV_ILLEGAL_ACTION_PENALTY:-0.25}"
export GOV_HARD_FACT_WEIGHT="${GOV_HARD_FACT_WEIGHT:-0.70}"
export GOV_PROCESS_WEIGHT="${GOV_PROCESS_WEIGHT:-0.25}"
export GOV_EXPRESSION_WEIGHT="${GOV_EXPRESSION_WEIGHT:-0.05}"
export GOV_JUDGE_FAILURE_SCORE="${GOV_JUDGE_FAILURE_SCORE:-0.0}"
